### ISSUE TITLE
linkify.match gets stuck with string containing a lot of emoji

### ISSUE THREAD

**Issue by eramdam** [markdown-it/linkify-it#36] opened 2016-05-27 22:50 UTC
We (the company I work at) run `linkify-it` on various email/text content to auto-link stuff. It works pretty great, however we encountered some cases where the `.match` function gets stuck because of a big (?) number of emoji/unicode character. Here is one of those string as an example (with fake text for privacy)

https://gist.github.com/eramdam/d743452c916e90ff7b42720f4384088e

I managed to avoid the hang by setting `fuzzyLink: true` so I guess the regexes used for that are probably subject to slowness on such strings.

**Comment by puzrin** [comment] 2016-05-27 22:58
Hm... that's really strange. There should be no such regexes and `fuzzyLink: true` should not be related. We cared about such situations.

[online demo](http://markdown-it.github.io/linkify-it/#t1=Lorem%20ipsum%20dolor%20sit%20amet%2C%20consectetur%20adipisicing%20elit%2C%20sed%20do%20eiusmod%20tempor%20incididunt%20ut%20labore%20et%20dolore%20magna%20aliqua.%20Ut%20enim%20ad%20minim%20veniam%2C%20quis%20n%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1Lorem%20ipsum%20dolor%20sit%F0%9F%98%88%F0%9F%98%88%F0%9F%98%88%F0%9F%98%88%F0%9F%98%88%F0%9F%98%88%F0%9F%98%88%F0%9F%98%88%F0%9F%98%88%F0%9F%98%88%F0%9F%98%88%F0%9F%98%88%F0%9F%98%88%F0%9F%98%88%F0%9F%98%88%F0%9F%98%88%F0%9F%98%88%F0%9F%98%88%F0%9F%98%88%F0%9F%98%88%F0%9F%98%88%F0%9F%98%88Lorem%20ipsum%20dolor%20sit%20amet%2C%20consectetur%F0%9F%98%87%F0%9F%98%87%F0%9F%98%87%F0%9F%98%87%F0%9F%98%87%F0%9F%98%87%F0%9F%98%87%F0%9F%98%87%F0%9F%98%87%F0%9F%98%84)

See the link above, can't reproduce hang you have. Could you prepare test repo with minimal example?

**Comment by eramdam** [comment] 2016-05-28 03:05
Oh shoot I wanted to say that I managed to avoid the issue by setting `fuzzyLink` to **`false`**. I wrote my issue a little took quickly 😓 

I added a PoC.js file in the gist linked earlier https://gist.github.com/eramdam/d743452c916e90ff7b42720f4384088e

Try to switch `fuzzyLink` to false/true to see. Running node v6.2.0

**Comment by puzrin** [comment] 2016-05-28 03:36
Hm... still can't reproduce, checked in node 6 latest and node 4 latest. Your gist has typos, here is one i used after fixes https://gist.github.com/puzrin/b573e94015f11c71e048e52a42b6db43

Difference with fuzzy on/off is almost not visible. Could you clarify your example?

**Comment by eramdam** [comment] 2016-05-28 04:20
The two last lines on the string in PoC.js were actually very important because they are the one that triggers the issue for me. Specifically the `abcd://abcdeghi.com` part. 

```javascript
const str = 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis n😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡Lorem ipsum dolor sit😈😈😈😈😈😈😈😈😈😈😈😈😈😈😈😈😈😈😈😈😈😈Lorem ipsum dolor sit amet, consectetur😇😇😇😇😇😇😇😇😇😄AAUID: 234567876543456 Sent via: abcd://abcdeghi.com';
const res = BaseFunc(str);
```

I recorded the situation if that might help https://asciinema.org/a/57ojqri3hvpuly7brol6izt1w

**Comment by eramdam** [comment] 2016-05-28 04:29
More details:

With `fuzzyLink: true`
- The string `Lorem ipsum dolor sit amet, consectetur😇😇😇😇😇😇😇😇😇😄AAUID: 234567876543456 Sent via: abcd://abcdeghi.com` is processed finely (~20ms)
- The string `😈😈😈😈😈😈😈😈😈😈😈😈😈😈😈😈😈😈😈😈😈😈Lorem ipsum dolor sit amet, consectetur😇😇😇😇😇😇😇😇😇😄AAUID: 234567876543456 Sent via: abcd://abcdeghi.com` starts to slow down the process where it takes ~430ms to process it
- The string `😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡Lorem ipsum dolor sit😈😈😈😈😈😈😈😈😈😈😈😈😈😈😈😈😈😈😈😈😈😈Lorem ipsum dolor sit amet, consectetur😇😇😇😇😇😇😇😇😇😄AAUID: 234567876543456 Sent via: abcd://abcdeghi.com` starts to be pretty long to process (~3.7sec) and it gets worse the more emoji get added to the string.

And when I set `fuzzyLink` to `false` everything runs fine in 15ms.

**Comment by puzrin** [comment] 2016-05-28 04:43
Reproduced :(. Pattern is `'😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡 .com'`

`.com` needed to pass simple check that fuzzy link may exist. @rlidwka take a look please

**Comment by puzrin** [comment] 2016-05-28 04:47
This pattern also crashes online demo.

**Comment by puzrin** [comment] 2016-05-28 13:11
Possible workarounds:

1. Reoptimize `uc.micro` regex to use `u` flags when available. Problem - may be can fix node (not sure), but still sucks with old browsers.
  - for old browsers we can drop astral matches before TLDs in fuzzy links.
2. Split fuzzy search to have strong start (or end) points:
   - search `.TLD/valid_path`. In this case pattern `.TLD` is simple & unique enougth to limit possible scans.
   - validate matching prefix before `.TLD`. In this case `$` can help. If not - we can write back-direction scanner.

**Closed** 2016-05-30 14:03 UTC
Labels: bug

**Comment by puzrin** [comment] 2016-05-30 14:14
[Fixed](http://markdown-it.github.io/linkify-it/#t1=%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%F0%9F%98%A1%20.com)

Thanks for your help!

New install will load fixed `uc.micro`, but i released a new version with bumped dependencies for sure.

**Comment by eramdam** [comment] 2016-05-30 17:10
Awesome! Glad to help, and thanks for the insanely fast response 👍

**Comment by puzrin** [comment] 2016-05-31 19:18
Seems you've been interested in #26. Do you have stats about links with `<` & `>` ? I'm not sure that `< >` comes in pairs like `(...)` and `[...]`.

I could suggest such kludge: if `http(s)://` is prepended with `<`, then drop in found link everything after `>`. But not sure how safe is it.

**Comment by eramdam** [comment] 2016-05-31 19:53
@puzrin it's "common" in text version of automatic emails so yes  `>` and `<` come in pair. The tricky thing is not to match the trailing `>` as part of the URL, sounds prety safe to me since these are characters that are supposed to be in URLs AFAIK.

**Comment by puzrin** [comment] 2016-05-31 19:59
So, you suggest to drop `>` only if it is the last character in link and `<` come before `http://` ?

Under "pairs" i meaned location inside links ~ like `http://example.com/foo_bar_(wiki)`

**Comment by puzrin** [comment] 2016-05-31 20:01
May be you have some stat when `<` or `>` can be used in link? Need examples to meditate over :)

**Comment by eramdam** [comment] 2016-05-31 20:35
I don't have specific statistics, but it's used A LOT for emails also. And no I don't think `>`and `<`are supposed to be contained inside a valid URL:

given this `<http://domain.com/foo_bar_(wiki)>` then the parsed URL should be `http://domain.com/foo_bar_(wiki)`. 

Here are some examples I can get from the top of my head:
```
<http://domain.com>
<user@domain.com>
```

**Comment by puzrin** [comment] 2016-05-31 22:57
Try version from master. I don't know is it correct https://github.com/markdown-it/linkify-it/commit/c502c8bc3028045d40abcbebf84c20e2afd17c0e.

`<` & `>` were disabled in links, including path & query.

**Comment by eramdam** [comment] 2016-06-01 03:38
Will try that asap

**Comment by eramdam** [comment] 2016-06-01 18:08
@puzrin I tried and it seems good to me, works as expected! 👍 👌

**Comment by puzrin** [comment] 2016-06-01 19:03
I've asked guys from disapora & npm to inspect this change for sure. If they will not find any edge cases, i'll do "official" release.
