### ISSUE TITLE
url not detected correctly

### ISSUE THREAD

**Issue by ysdnoproject** [markdown-it/linkify-it#57] opened 2018-02-02 06:09 UTC
For example:
String:  "就是这个www.meishi.com 好吃"
result: 
![image](https://user-images.githubusercontent.com/13352483/35719093-ff41be66-082a-11e8-820a-122d2939536f.png)

I think Chinese should not match as part of url.

**Comment by handycode** [comment] 2018-03-09 11:02
I have the same problem:
```
md: 你好https://google.com
expert: <p>你好<a href='https://google.com'>https://google.com</a></p>
output: <p>你好https://google.com</p>
```

**Comment by handycode** [comment] 2018-03-14 04:37
and ...
```
text: 1.web
output: <a href='http://1.web'>1.web</a>
```

**Comment by puzrin** [comment] 2021-11-30 06:35
IMO that's dupe of #15 (i see no principal difference).

Closing, but can reopen back if required,

**Closed by puzrin** 2021-11-30 06:35 UTC
