### ISSUE TITLE
URL with more than one exclamation mark breaks

### ISSUE THREAD

**Issue by realies** [markdown-it/linkify-it#69] opened 2018-07-31 13:27 UTC
As the title states, URL detection stops at the first instance of more than one exclamation mark.

**Comment by christer88** [comment] 2018-07-31 13:51
**Example:**
https://img.alicdn.com/imgextra/i4/128600268/TB2iGrkacwb61Bjy0FfXXXvlpXa_!!128600268.jpg

**Comment by astorije** [comment] 2018-09-13 05:01
Maybe related to #63?

**Comment by puzrin** [comment] 2019-04-03 21:48
Dupe of #54

**Closed by puzrin** 2019-04-03 21:48 UTC
