### ISSUE TITLE
Triple dash ( --- ) terminating the parsing

### ISSUE THREAD

**Issue by pablolmiranda** [markdown-it/linkify-it#27] opened 2015-12-12 00:50 UTC
Hi,

Why [triple dash](https://github.com/markdown-it/linkify-it/blob/master/lib/re.js#L56) terminate the url parsing?

**Comment by puzrin** [comment] 2015-12-12 01:01
As written in comment `---` is usually a long dash.

**Comment by stephy** [comment] 2015-12-15 06:31
@puzrin I am aware that --- is a long dash, but why is the long dash a problem? Some google docs have --- in their URL and they are legit URLs.

**Comment by puzrin** [comment] 2015-12-15 06:41
@stephy `link---text` is link + long dash + text, in markdown (for example). That happens sometime, and that should not become a long link. As alternative, user can mark link explicitely: `<link---with---dashes>`.

False negative (terminated link) still leaves you an alternative way to fix situation. False positive (too long link) is not fixeable.

**Comment by puzrin** [comment] 2016-01-10 04:32
Closing - works as intended.

**Closed by puzrin** 2016-01-10 04:32 UTC
Labels: question

**Comment by puzrin** [comment] 2016-06-22 12:12
Fixed in 2.0.0, now configurable via options and not terminates by default.
