### ISSUE TITLE
Url not detected correctly

### ISSUE THREAD

**Issue by BusinessDuck** [markdown-it/linkify-it#79] opened 2019-11-13 14:44 UTC
Example url : 
`https://tc.myproj.com/httpAuth/app/rest/changes?locator=build:(running:any,sinceBuild:(buildType:My_BUILD_TYPE,status:SUCCESS))&fields=change(comment)`

Matched result:

`https://tc.myproj.com/httpAuth/app/rest/changes?locator=build:(running:any,sinceBuild:(buildType:My_BUILD_TYPE,status:SUCCESS))`

Missing part: 
`&fields=change(comment)`

**Comment by puzrin** [comment] 2020-05-18 13:24
Seems dupe of #23. Current implementation does not allow easy handle of nested patterns. Also, we can not blind allow multiple `)))` due false positives for such case:

```
(text https://tc.myproj.com/httpAuth/app/rest/changes?locator=build:(running:any,sinceBuild:(buildType:My_BUILD_TYPE,status:SUCCESS)))
```

There are no way to detect where to stop without true nested parser.

I've added reference to #23 and closing this as dupe.

**Closed by puzrin** 2020-05-18 13:24 UTC
