### ISSUE TITLE
Double closing curly braces ( }} ) seem to break the detection

### ISSUE THREAD

**Issue by eramdam** [markdown-it/linkify-it#52] opened 2017-04-28 17:24 UTC
Consider this string

```
Here is a link https://domain.com/d/foo?email={{foo.bar}}&name={{foo.name}}
```
Even though curly braces are not common in URL, one would expect for `https://domain.com/d/foo?email={{foo.bar}}&name={{foo.name}}` to be matched to an actual link.

However linkify-it seems to stop matching after the 2nd `}` character in the URL, resulting in these matches:

```javascript
[ Match {
    schema: 'https:',
    index: 3,
    lastIndex: 44,
    raw: 'https://domain.com/d/foo?email={{foo.bar}',
    text: 'https://domain.com/d/foo?email={{foo.bar}',
    url: 'https://domain.com/d/foo?email={{foo.bar}' },
  Match {
    schema: '',
    index: 53,
    lastIndex: 61,
    raw: 'foo.name',
    text: 'foo.name',
    url: 'http://foo.name' } ]
```

Notice how `foo.name` is being matched as another link because of that 😅  

Once again, I know that `{` and `}` are not valid characters per the RFC, but Slack and other softwares correctly match this case so I guess there's something that can be done to fix that in linkify-it 😊 

I'm happy to provide more details/examples.

**Comment by puzrin** [comment] 2017-04-28 17:41
Looks like dupe of https://github.com/markdown-it/linkify-it/issues/23. IMHO worth to RIP one more example there :)

**Comment by puzrin** [comment] 2017-04-28 17:48
I thinks this does not needs fix in linkify-it, but you can add kludge to your app: replace `{{` and `}}` with something unique and non-breaking-link, and replace back after linkify run. That's dirty, but may be ok for your specific case.

**Comment by githubflub** [comment] 2017-12-01 05:15
This is still an issue. >:[

**Comment by puzrin** [comment] 2021-11-30 06:33
@eramdam hi after many years :). I'd like to clarify status of this issue.

- is it critical or can be rejected?
- should we consider it as part of #23 or as special case?

**Comment by puzrin** [comment] 2022-04-18 12:47
Close as dupe of #23

**Closed by puzrin** 2022-04-18 12:47 UTC
